export const regionToGroup: Record<string, string> = {
  "Gaza (near a medical centre)": "Gaza",
  "Northern Gaza (near aid distribution)": "Northern Gaza",
  "Gaza Strip (various)": "Gaza Strip",
  "Northern Gaza (aid queue site)": "Northern Gaza",
  "Gaza City (residential)": "Gaza City",
  "Gaza Strip (food/humanitarian context)": "Gaza Strip",
  "Deir al-Balah / Central Gaza": "Central Gaza",
  "Northern Gaza (Zikim entry routes / aid queues)": "Northern Gaza",
  "Southern Gaza (aid convoy area)": "Southern Gaza",
  "Gaza (various) - aid access context": "Gaza",
  "Gaza City (al-Tuffah / Al-Ahli area)": "Gaza City",
  "Northern Gaza (aid/queue sites)": "Northern Gaza",
  "Rafah / aid site region": "Southern Gaza",
  "Northern Gaza (food distribution centre)": "Northern Gaza",
  "Khan Younis / aid queue areas": "Southern Gaza",
  "Northern Gaza (Zikim crossing area)": "Northern Gaza",
  "Gaza City (residential neighbourhoods)": "Gaza City",
  "Gaza City (central market)": "Gaza City",
  "Beit Lahia (north Gaza)": "Northern Gaza",
  "Gaza (hospital site)": "Gaza",
};
